/*
 * This file is generated by jOOQ.
 */
package com.vominh.example.jooq.generate;


import com.vominh.example.jooq.generate.tables.Device;
import com.vominh.example.jooq.generate.tables.records.DeviceRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DeviceRecord> PK_DEVICE = Internal.createUniqueKey(Device.DEVICE, DSL.name("pk_device"), new TableField[] { Device.DEVICE.ID }, true);
}
