/*
 * This file is generated by jOOQ.
 */
package com.vominh.example.jooq.generate;


import com.vominh.example.jooq.generate.tables.Device;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.device</code>.
     */
    public static final Device DEVICE = Device.DEVICE;
}
